# Dataset Preprocessing

## Train set

In [2]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import numpy as np
import cPickle
from difflib import SequenceMatcher
# import geocoder

def similar(a, b):
    return SequenceMatcher(None, a, b).ratio()

pd.options.display.max_columns = 60
pd.options.display.max_columns = 100

In [3]:
df_all = pd.read_json('train.json')
df_test = pd.read_json('test.json')

In [6]:
df_all.head(2)

,bathrooms,bedrooms,building_id,created,description,display_address,features,interest_level,latitude,listing_id,longitude,manager_id,photos,price,street_address,num_photos,num_desc,num_feats
10,1.5,3,53a5b119ba8f7b61d4e010512e0dfc85,2016-06-24 07:54:24,A Brand New 3 Bedroom 1.5 bath ApartmentEnjoy ...,Metropolitan Avenue,[],medium,40.7145,7211212,-73.9425,5ba989232d0489da1b5f2c45f6688adc,[https://photos.renthop.com/2/7211212_1ed4542e...,3000,792 Metropolitan Avenue,5,588,0
10000,1.0,2,c5c8a357cba207596b04d1afd1e4f130,2016-06-12 12:19:27,,Columbus Avenue,"[Doorman, Elevator, Fitness Center, Cats Allow...",low,40.7947,7150865,-73.9667,7533621a882f71e25173b27e3139d83d,[https://photos.renthop.com/2/7150865_be3306c5...,5465,808 Columbus Avenue,11,8,5

In [5]:
df_all['num_photos'] = df_all['photos'].apply(lambda x: len(x))
df_test['num_photos'] = df_test['photos'].apply(lambda x: len(x))
df_all['num_desc'] = df_all['description'].apply(lambda x: len(x))
df_test['num_desc'] = df_test['description'].apply(lambda x: len(x))
df_all['num_feats'] = df_all['features'].apply(lambda x: len(x))
df_test['num_feats'] = df_test['features'].apply(lambda x: len(x))

In [36]:
# from geopy.geocoders import Nominatim
# geolocator = Nominatim()
# def get_neighborhood_2(x):
#     location = geolocator.reverse(str(x['latitude']) + ',' + str(x['longitude']))
#     loc = location.raw
# #     print loc['address']['neighbourhood']
#     return loc

In [37]:
# df_all['raw_location'] = df_all.apply(get_neighborhood_2, axis=1)

In [38]:
# def get_neighborhood(x):
#     g = geocoder.google([x['latitude'], x['longitude']], method='reverse')
#     return g.neighborhood

In [39]:
# df_test['neighborhood'] = df_test.apply(get_neighborhood, axis=1)

In [7]:
drop_list = [#u'building_id',
#  u'created',
#  u'description',# --- look for specific words
#  u'display_address',
#  u'features',# --- make dummy variables
#  u'listing_id',
# u'manager_id',
 u'photos',# --- number of photos
 u'street_address']#,
#'longitude',
#'latitude']

df_all.drop(drop_list, axis=1, inplace=True)

df_test.drop(drop_list, axis=1, inplace=True)

## 'created' feature

In [8]:
df_all.created = pd.to_datetime(df_all.created, format='%Y-%m-%d %H:%M:%S')# - np.datetime64('1970-01-01T00:00:00Z')
# ts = (dt64 - np.datetime64('1970-01-01T00:00:00Z')) / np.timedelta64(1, 's')
df_all.created = df_all.created.apply(lambda x: (x - np.datetime64('1970-01-01T00:00:00Z')) / np.timedelta64(1, 's'))

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:3: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  app.launch_new_instance()

In [9]:
df_test.created = pd.to_datetime(df_test.created, format='%Y-%m-%d %H:%M:%S')# - np.datetime64('1970-01-01T00:00:00Z')
df_test.created = df_test.created.apply(lambda x: (x - np.datetime64('1970-01-01T00:00:00Z')) / np.timedelta64(1, 's'))

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  from ipykernel import kernelapp as app

In [10]:
df_all.head()

,bathrooms,bedrooms,building_id,created,description,display_address,features,interest_level,latitude,listing_id,longitude,manager_id,price,num_photos,num_desc,num_feats
10,1.5,3,53a5b119ba8f7b61d4e010512e0dfc85,1.466755e+09,A Brand New 3 Bedroom 1.5 bath ApartmentEnjoy ...,Metropolitan Avenue,[],medium,40.7145,7211212,-73.9425,5ba989232d0489da1b5f2c45f6688adc,3000,5,588,0
10000,1.0,2,c5c8a357cba207596b04d1afd1e4f130,1.465734e+09,,Columbus Avenue,"[Doorman, Elevator, Fitness Center, Cats Allow...",low,40.7947,7150865,-73.9667,7533621a882f71e25173b27e3139d83d,5465,11,8,5
100004,1.0,1,c3ba40552e2120b0acfc3cb5730bb2aa,1.460864e+09,"Top Top West Village location, beautiful Pre-w...",W 13 Street,"[Laundry In Building, Dishwasher, Hardwood Flo...",high,40.7388,6887163,-74.0018,d9039c43983f6e564b1482b273bd7b01,2850,8,691,4
100007,1.0,1,28d9ad350afeaab8027513a3e52ac8d5,1.460946e+09,Building Amenities - Garage - Garden - fitness...,East 49th Street,"[Hardwood Floors, No Fee]",low,40.7539,6888711,-73.9677,1067e078446a7897d2da493d2f741316,3275,3,492,2
100013,1.0,4,0,1.461807e+09,Beautifully renovated 3 bedroom flex 4 bedroom...,West 143rd Street,[Pre-War],low,40.8241,6934781,-73.9493,98e13ad4b495b9613cef886d79a6291f,3350,3,479,1

In [43]:
# df_all['created_norm'] = df_all.created - min(df_all.created)

In [44]:
# df_all.head(2)

In [45]:
# df_all.created_norm.head(5)

In [46]:
# df_all.boxplot('created_norm', by='interest_level', figsize=(12, 8))

## 'features' feature

In [11]:
unique_features = {}
for i in range(df_all.shape[0]):
    for f in df_all.features.iloc[i]:
        f = f.lower()
        if f in unique_features.keys():
            unique_features[f] += 1
        else:
            unique_features[f] = 1

import operator
sorted_x = sorted(unique_features.items(), key=operator.itemgetter(1), reverse=True)

print len(unique_features.keys())
# print sorted_x

subdict = dict((k,unique_features[k]) for k in unique_features.keys() if unique_features[k]>1)
sorted_x = sorted(subdict.items(), key=operator.itemgetter(1), reverse=True)
print len(subdict.keys())
# 1294
# 458

1294
458

In [12]:
subdict2 = dict((k,unique_features[k]) for k in unique_features.keys() if unique_features[k]>10)
sorted_x2 = sorted(subdict2.items(), key=operator.itemgetter(1), reverse=True)
print len(subdict2.keys())
# 161

161

In [13]:
top_feats = [sorted_x2[i][0] for i in range(len(subdict2.keys()))]
# for f in top_feats:
#     print "similar_colnames['" + f + "'] = ''"

In [14]:
similar_colnames = {}

for f1 in top_feats:
    for f2 in top_feats[top_feats.index(f1)+1:]:
        if similar(f1, f2)  > 0.84:
            similar_colnames[f2] = f1

similar_colnames[u'roofdeck'] = 'roof deck'
similar_colnames['laundry in unit'] = 'laundry in building'
similar_colnames['laundry room'] = 'laundry in building'
similar_colnames['laundry'] = 'laundry in building'
similar_colnames['washer in unit'] = 'laundry in building'
similar_colnames['dryer in unit'] = 'laundry in building'
similar_colnames['on-site laundry'] = 'laundry in building'
similar_colnames['common outdoor space'] = 'outdoor space'
similar_colnames['publicoutdoor'] = 'outdoor space'
similar_colnames['pool'] = 'swimming pool'
similar_colnames['concierge'] = 'doorman'
similar_colnames['newly renovated'] = 'renovated'
similar_colnames['hardwood'] = 'hardwood floors'
similar_colnames['patio'] = 'garden/patio'
similar_colnames['washer/dryer'] = 'laundry in building'
similar_colnames['live-in superintendent'] = 'live in super'
similar_colnames['gym/fitness'] = 'fitness center'
similar_colnames['garden'] = 'garden/patio'
similar_colnames['eat in kitchen'] = 'dining room'
similar_colnames['eat-in kitchen'] = 'dining room'
similar_colnames['lounge'] = 'residents lounge'
similar_colnames['common parking/garage'] = 'parking space'
similar_colnames['parking'] = 'parking space'
similar_colnames['full-time doorman'] = 'doorman'
similar_colnames['wifi access'] = 'high speed internet'
similar_colnames['gym'] = 'fitness center'
similar_colnames['luxury building'] = 'exclusive'
similar_colnames['residents garden'] = 'garden/patio'
similar_colnames['common roof deck'] = 'roof deck'
similar_colnames['outdoor areas'] = 'outdoor space'
similar_colnames['indoor pool'] = 'swimming pool'
similar_colnames['lounge room'] = 'residents lounge'
similar_colnames['building-common-outdoor-space'] = 'outdoor space'
similar_colnames['valet parking'] = 'valet'
similar_colnames['air conditioning'] = 'central a/c'
similar_colnames['washer & dryer'] = 'laundry in building'
similar_colnames['private balcony'] = 'balcony'
similar_colnames['courtyard'] = 'garden/patio'
similar_colnames['on-site super'] = 'live in super'
similar_colnames['wheelchair ramp'] = 'wheelchair access'
similar_colnames['private-balcony'] = 'balcony'
similar_colnames['health club'] = 'fitness center'
similar_colnames['full service garage'] = 'garage'
similar_colnames['washer/dryer in building'] = 'laundry in building'
similar_colnames['ft doorman'] = 'doorman'
similar_colnames['outdoor entertainment space'] = 'outdoor space'
similar_colnames['decorative fireplace'] = 'fireplace'
similar_colnames['on-site parking lot'] = 'parking space'
similar_colnames['basement storage'] = 'storage'
similar_colnames['hi rise'] = 'highrise'
similar_colnames['in-unit washer/dryer'] = 'laundry in building'
similar_colnames['private-outdoor-space'] = 'outdoor space'
similar_colnames['on-site parking'] = 'parking space'
similar_colnames['private terrace'] = 'terrace'
similar_colnames['common terrace'] = 'terrace'
similar_colnames['concierge service'] = 'doorman'
similar_colnames['deck'] = 'roof deck'
similar_colnames['private backyard'] = 'garden/patio'
similar_colnames['cats allowed'] = 'pet friendly'
similar_colnames['dogs allowed'] = 'pet friendly'
similar_colnames['storage room'] = 'storage'
similar_colnames['assigned-parking-space'] = 'parking space'
similar_colnames['rooftop terrace'] = 'roof deck'
similar_colnames['private parking'] = 'parking space'
similar_colnames['backyard'] = 'garden/patio'
similar_colnames['common garden'] = 'garden/patio'
similar_colnames['common backyard'] = 'garden/patio'
similar_colnames['pets allowed'] = 'pet friendly'
similar_colnames['rooftop deck'] = 'roof deck'
similar_colnames['playroom/nursery'] = 'childrens playroom'
similar_colnames['terraces / balconies'] = 'terrace'
similar_colnames['bike storage'] = 'bike room'
similar_colnames['laundry on floor'] = 'laundry in building'
similar_colnames['outdoor pool'] = 'swimming pool'
similar_colnames['screening room'] = 'community recreation facilities'
similar_colnames['washer/dryer in unit'] = 'laundry in building'
similar_colnames['mail room'] = 'package room'
similar_colnames['shared backyard'] = 'garden/patio'
similar_colnames['on-site garage'] = 'garage'
# similar_colnames

In [15]:
print len(top_feats), len(similar_colnames.keys())
top_feats = [x for x in top_feats if not x in similar_colnames.keys()]
print len(top_feats)
# 161 88
# 73

161 88
73

In [16]:
top_feats[:5]
# [u'elevator',
#  u'hardwood floors',
#  u'doorman',
#  u'dishwasher',
#  u'laundry in building']

[u'elevator',
 u'hardwood floors',
 u'doorman',
 u'dishwasher',
 u'laundry in building']

In [17]:
cPickle.dump(top_feats, open('cat_feats.p', 'wb'))

In [18]:
for colname in top_feats:
    df_all[colname] = 0
    df_test[colname] = 0
# df_all.head(2)

In [19]:
df_all.reset_index(inplace=True)
df_test.reset_index(inplace=True)

In [20]:
df_all.shape
# (49352, 90)

(49352, 90)

In [21]:
for i in range(df_all.shape[0]):
    features = [x.lower() for x in df_all.features.iloc[i]]
    for feat in features: 
        if feat in df_all.columns:
            df_all.set_value(index = i, col = feat, value = 1)
        elif feat in similar_colnames.keys():
            df_all.set_value(index = i, col = similar_colnames[feat], value = 1)

In [22]:
df_test.shape
# (74659, 84)

(74659, 89)

In [23]:
for i in range(df_test.shape[0]):
    features = [x.lower() for x in df_test.features.iloc[i]]
    for feat in features: 
        if feat in df_test.columns:
            df_test.set_value(index = i, col = feat, value = 1)
        elif feat in similar_colnames.keys():
            df_test.set_value(index = i, col = similar_colnames[feat], value = 1)

In [24]:
# df_all.iloc[6]['description']
df_all.head(2)

,index,bathrooms,bedrooms,building_id,created,description,display_address,features,interest_level,latitude,listing_id,longitude,manager_id,price,num_photos,num_desc,num_feats,elevator,hardwood floors,doorman,dishwasher,laundry in building,no fee,fitness center,pre-war,roof deck,outdoor space,dining room,high speed internet,balcony,swimming pool,new construction,terrace,exclusive,loft,garden/patio,wheelchair access,fireplace,simplex,lowrise,garage,reduced fee,furnished,multi-level,high ceilings,private outdoor space,parking space,live in super,renovated,green building,storage,stainless steel appliances,light,granite kitchen,bike room,exposed brick,marble bath,pets on approval,walk in closet(s),valet,subway,residents lounge,highrise,short term allowed,childrens playroom,no pets,duplex,actual apt. photos,central a/c,view,live/work,virtual doorman,sauna,microwave,shares ok,post-war,brownstone,business center,sublet,midrise,pet friendly,guarantors accepted,attended lobby,package room,video intercom,community recreation facilities,skylight,flex-2,cable/satellite tv,all utilities included
0,10,1.5,3,53a5b119ba8f7b61d4e010512e0dfc85,1.466755e+09,A Brand New 3 Bedroom 1.5 bath ApartmentEnjoy ...,Metropolitan Avenue,[],medium,40.7145,7211212,-73.9425,5ba989232d0489da1b5f2c45f6688adc,3000,5,588,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,10000,1.0,2,c5c8a357cba207596b04d1afd1e4f130,1.465734e+09,,Columbus Avenue,"[Doorman, Elevator, Fitness Center, Cats Allow...",low,40.7947,7150865,-73.9667,7533621a882f71e25173b27e3139d83d,5465,11,8,5,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0

In [25]:
for i in range(df_all.shape[0]):
    if i in [10, 100, 200, 500, 800]:
        print i
    if i%1000 ==0:
        print i
    for feat in top_feats: 
        if feat in df_all.iloc[i]['description']:
            df_all.set_value(index = i, col = feat, value = 1)
    for feat in similar_colnames.keys():
        if feat in df_all.iloc[i]['description']:
            df_all.set_value(index = i, col = similar_colnames[feat], value = 1)
# 49000

0
10
100
200
500
800
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000

In [26]:
for i in range(df_test.shape[0]):
    if i in [10, 100, 200, 500, 800]:
        print i
    if i%1000 ==0:
        print i
    for feat in top_feats: 
        if feat in df_test.iloc[i]['description']:
            df_test.set_value(index = i, col = feat, value = 1)
    for feat in similar_colnames.keys():
        if feat in df_test.iloc[i]['description']:
            df_test.set_value(index = i, col = similar_colnames[feat], value = 1)
# 490000

0
10
100
200
500
800
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000

In [75]:
# df_all.set_index('index', inplace=True)
# df_test.set_index('index', inplace=True)

In [27]:
df_all.head(3)

,index,bathrooms,bedrooms,building_id,created,description,display_address,features,interest_level,latitude,listing_id,longitude,manager_id,price,num_photos,num_desc,num_feats,elevator,hardwood floors,doorman,dishwasher,laundry in building,no fee,fitness center,pre-war,roof deck,outdoor space,dining room,high speed internet,balcony,swimming pool,new construction,terrace,exclusive,loft,garden/patio,wheelchair access,fireplace,simplex,lowrise,garage,reduced fee,furnished,multi-level,high ceilings,private outdoor space,parking space,live in super,renovated,green building,storage,stainless steel appliances,light,granite kitchen,bike room,exposed brick,marble bath,pets on approval,walk in closet(s),valet,subway,residents lounge,highrise,short term allowed,childrens playroom,no pets,duplex,actual apt. photos,central a/c,view,live/work,virtual doorman,sauna,microwave,shares ok,post-war,brownstone,business center,sublet,midrise,pet friendly,guarantors accepted,attended lobby,package room,video intercom,community recreation facilities,skylight,flex-2,cable/satellite tv,all utilities included
0,10,1.5,3,53a5b119ba8f7b61d4e010512e0dfc85,1.466755e+09,A Brand New 3 Bedroom 1.5 bath ApartmentEnjoy ...,Metropolitan Avenue,[],medium,40.7145,7211212,-73.9425,5ba989232d0489da1b5f2c45f6688adc,3000,5,588,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,10000,1.0,2,c5c8a357cba207596b04d1afd1e4f130,1.465734e+09,,Columbus Avenue,"[Doorman, Elevator, Fitness Center, Cats Allow...",low,40.7947,7150865,-73.9667,7533621a882f71e25173b27e3139d83d,5465,11,8,5,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,100004,1.0,1,c3ba40552e2120b0acfc3cb5730bb2aa,1.460864e+09,"Top Top West Village location, beautiful Pre-w...",W 13 Street,"[Laundry In Building, Dishwasher, Hardwood Flo...",high,40.7388,6887163,-74.0018,d9039c43983f6e564b1482b273bd7b01,2850,8,691,4,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [39]:
print df_all.shape
print df_test.shape
# (49352, 85)
# (74659, 84)

(49352, 90)
(74659, 87)

In [29]:
# df_all.drop(['description', 'features'], axis=1)
df_test.drop(['description', 'features'], axis=1, inplace=True)

In [30]:
# df_all_clean.head()

In [31]:
# df_all.to_csv('train_feats_max.csv', index=None)

In [33]:
# df_all.to_csv('train_feats_w_ids.csv', index=None)
# df_test.to_csv('test_feats_w_ids.csv', index=None)

In [40]:
df_all.to_json('train_feats_w_ids.json')
df_test.to_json('test_feats_w_ids.json')

In [41]:
df_all.head(3)

,index,bathrooms,bedrooms,building_id,created,description,display_address,features,interest_level,latitude,listing_id,longitude,manager_id,price,num_photos,num_desc,num_feats,elevator,hardwood floors,doorman,dishwasher,laundry in building,no fee,fitness center,pre-war,roof deck,outdoor space,dining room,high speed internet,balcony,swimming pool,new construction,terrace,exclusive,loft,garden/patio,wheelchair access,fireplace,simplex,lowrise,garage,reduced fee,furnished,multi-level,high ceilings,private outdoor space,parking space,live in super,renovated,green building,storage,stainless steel appliances,light,granite kitchen,bike room,exposed brick,marble bath,pets on approval,walk in closet(s),valet,subway,residents lounge,highrise,short term allowed,childrens playroom,no pets,duplex,actual apt. photos,central a/c,view,live/work,virtual doorman,sauna,microwave,shares ok,post-war,brownstone,business center,sublet,midrise,pet friendly,guarantors accepted,attended lobby,package room,video intercom,community recreation facilities,skylight,flex-2,cable/satellite tv,all utilities included
0,10,1.5,3,53a5b119ba8f7b61d4e010512e0dfc85,1.466755e+09,A Brand New 3 Bedroom 1.5 bath ApartmentEnjoy ...,Metropolitan Avenue,[],medium,40.7145,7211212,-73.9425,5ba989232d0489da1b5f2c45f6688adc,3000,5,588,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,10000,1.0,2,c5c8a357cba207596b04d1afd1e4f130,1.465734e+09,,Columbus Avenue,"[Doorman, Elevator, Fitness Center, Cats Allow...",low,40.7947,7150865,-73.9667,7533621a882f71e25173b27e3139d83d,5465,11,8,5,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,100004,1.0,1,c3ba40552e2120b0acfc3cb5730bb2aa,1.460864e+09,"Top Top West Village location, beautiful Pre-w...",W 13 Street,"[Laundry In Building, Dishwasher, Hardwood Flo...",high,40.7388,6887163,-74.0018,d9039c43983f6e564b1482b273bd7b01,2850,8,691,4,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [44]:
rd1 = pd.read_json('train_feats_w_ids.json')
rd2 = pd.read_json('test_feats_w_ids.json')

In [45]:
print rd1.shape
print rd2.shape

(49352, 90)
(74659, 87)